using System;
namespace P5GenralML
{
    public class Contact
    {
        public int ContactId { get; set; }
        public int UserInfoUserId { get; set; }
        public int UserGroupId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string AlternateEmailIds { get; set; }
        public string PhoneNumber { get; set; }
        public string AlternatePhoneNumbers { get; set; }
        public short? Unsubscribe { get; set; }
        public short LeadType { get; set; } = 0;
        public string ProfilePic { get; set; }
        public string Gender { get; set; }
        public DateTime? Age { get; set; }
        public string AgeRange { get; set; }
        public string MaritalStatus { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public string Interests { get; set; }
        public short KloutScore { get; set; } = 0;
        public string Location { get; set; }
        public string FacebookId { get; set; }
        public string FacebookUrl { get; set; }
        public string FacebookUserName { get; set; }
        public string TwitterId { get; set; }
        public string TwitterScreenName { get; set; }
        public string TwitterUserName { get; set; }
        public string TwitterUrl { get; set; }
        public string LinkedinId { get; set; }
        public string LinkedinUserName { get; set; }
        public string LinkedinUrl { get; set; }
        public string GoogleplusUrl { get; set; }
        public string YoutubeUrl { get; set; }
        public string PicasaUrl { get; set; }
        public string WordpressUrl { get; set; }
        public string VimeoUrl { get; set; }
        public string MyspaceUrl { get; set; }
        public string GravatarUrl { get; set; }
        public string FoursquareUrl { get; set; }
        public string KloutUrl { get; set; }
        public string YahooUrl { get; set; }
        public DateTime? FBLastUpdates { get; set; }
        public short? IsVerifiedMailId { get; set; }
        public short? IsVerifiedContactNumber { get; set; }
        public DateTime? CreatedDate { get; set; }
        public bool? LookedupStatus { get; set; }
        public short? AppType { get; set; } = 2;
        public string PinterestUrl { get; set; }
        public string AboutmeUrl { get; set; }
        public string InstagramUrl { get; set; }
        public string QuoraUrl { get; set; }
        public decimal? OverAllTimeSpentInSiteInSec { get; set; } = 0;
        public decimal? OverAllTimeSpentInChatInSec { get; set; } = 0;
        public int NoOfSession { get; set; } = 0;
        public int PastChatCount { get; set; } = 0;
        public int TotalChatCountSessionWise { get; set; } = 0;
        public string ReferralSourceList { get; set; }
        public int NumOfPageVisited { get; set; } = 0;
        public decimal? OverAllScore { get; set; } = 0;
        public int MailScore { get; set; } = 0;
        public int MailScoreType { get; set; } = 0;
        public int SMSScore { get; set; } = 0;
        public int SMSScoreType { get; set; } = 0;
        public string MemberId { get; set; }
        public short? BusinessUserIndividualUser { get; set; }
        public DateTime? LastPurchase { get; set; }
        public DateTime? LastMessageSent { get; set; }
        public short? HasOnlyOfflineTransactionTagType { get; set; } = 0;
        public double TotalLifeTimePurchaseValue { get; set; } = 0.0;
        public int TotalLifetimeTranCount { get; set; } = 0;
        public DateTime? RecentOnlineVisit { get; set; }
        public string ReferType { get; set; }
        public string UtmTagsList { get; set; }
        public string UtmTagSource { get; set; }
        public bool? USSDUnsubscribe { get; set; }
        public bool? IsSmsUnsubscribe { get; set; }
        public DateTime? SubscribedDate { get; set; }
        public short? OptInOverAllNewsLetter { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? SmsSubscribedDate { get; set; }
        public short? SmsOptInOverAllNewsLetter { get; set; }
        public DateTime? USSDSubscribedDate { get; set; }
        public short? USSDOptInOverAllNewsLetter { get; set; }
        public string Country { get; set; }
        public short? IsAppDownLoaded { get; set; }
        public DateTime? AppDownLoadedDate { get; set; }
        public short? IsAppRegistered { get; set; }
        public DateTime? AppRegisteredDate { get; set; }
        public string FirstUtmMedium { get; set; }
        public string FirstUtmCampaign { get; set; }
        public string FirstUtmTerm { get; set; }
        public string FirstUtmContent { get; set; }
        public string LastName { get; set; }
        public string ContactSource { get; set; }
        public bool? IsAccountHolder { get; set; }
        public string AccountType { get; set; }
        public string AccountOpenedSource { get; set; }
        public DateTime? LastActivityLoginDate { get; set; }
        public string LastActivityLoginSource { get; set; }
        public decimal? CustomerScore { get; set; }
        public decimal? AccountAmount { get; set; }
        public bool? IsCustomer { get; set; }
        public bool? IsMoneyTransferCustomer { get; set; }
        public bool? IsGoalSaver { get; set; }
        public bool? IsReferred { get; set; }
        public bool? IsReferredOpenedAccount { get; set; }
        public bool? IsComplaintRaised { get; set; }
        public string ComplaintType { get; set; }
        public string Project { get; set; }
        public DateTime? ProjectDate { get; set; }
        public bool? IsTCCustomer { get; set; }
        public string OriginalFICAInd { get; set; }
        public string CurrentFICAInd { get; set; }
        public bool? IsFundsDebit { get; set; }
        public bool? IsFundsGoalsave { get; set; }
        public string OriginatingChannel { get; set; }
        public bool? IsMoneyDeposited { get; set; }
        public string LoyaltyPoints { get; set; }
        public DateTime? LoyaltyPointsPeriod { get; set; }
        public string Rsaid { get; set; }
        public string StoreType { get; set; }
        public string StoreName { get; set; }
        public string Designation { get; set; }
        public string ProspectStage { get; set; }
        public string CountryCode { get; set; }
        public string RegistrationSource { get; set; }
        public bool? QualifiedForRewardsStore { get; set; }
        public DateTime? TCsVersionAccepted { get; set; }
        public string AccountNumber { get; set; }
        public DateTime? AccountDateTime { get; set; }
        public decimal? TransactionValue { get; set; }
        public string CaseNumber { get; set; }
        public int LoanApplicationId { get; set; }
        public int NumberOfDependents { get; set; }
        public decimal? Salary { get; set; }
        public decimal? ApplicantIncome { get; set; }
        public decimal? MonthlyIncome { get; set; }
        public decimal? LoanAmount { get; set; }
        public decimal? BalanceAmount { get; set; }
        public string TenureOfLoan { get; set; }
        public string CreditHistory { get; set; }
        public int CreditScore { get; set; }
        public string PropertyArea { get; set; }
        public bool? LoanStatus { get; set; }
        public bool? IsOwnHouse { get; set; }
        public bool? HasCreditCard { get; set; }
        public bool? IsActiveMember { get; set; }
        public int NumberOfAccountsHold { get; set; }
        public string StoryMessage { get; set; }
        public string Question { get; set; }
        public string QuestionID { get; set; }
        public string ApplicantId { get; set; }
        public string ProspectId { get; set; }
        public string AccountBranchName { get; set; }
        public string BureauType { get; set; }
        public string CityCategory { get; set; }
        public string CustomerId { get; set; }
        public string EcsActive { get; set; }
        public string EtpNtp { get; set; }
        public string SegmentType { get; set; }
        public string ContactSubSource { get; set; }
        public string AccountCardType { get; set; }
        public string AffluenceParameter { get; set; }
        public string AffluenceParameterRisk { get; set; }
        public bool? IsDeviceIdExists { get; set; }
        public short? IsAdSenseOrAdWord { get; set; }
        public int LastModifyByUserId { get; set; }
        public int LmsGroupId { get; set; }
        public string Remarks { get; set; }
        public DateTime? ReminderDate { get; set; }
        public string ToReminderPhoneNumber { get; set; }
        public string ToReminderEmailId { get; set; }
        public int Score { get; set; } = 0;
        public string SearchKeyword { get; set; }
        public string PageUrl { get; set; }
        public string ReferrerUrl { get; set; }
        public string Place { get; set; }
        public int MailTemplateId { get; set; }
        public DateTime? MailAlertScheduleDate { get; set; }
        public string FromEmailId { get; set; }
        public string Subject { get; set; }
        public string FromName { get; set; }
        public int SmsTemplateId { get; set; }
        public DateTime? SmsAlertScheduleDate { get; set; }
        public string CustomSmsContent { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string StateName { get; set; }
        public string ZipCode { get; set; }
        public string Religion { get; set; }
        public string DomainName { get; set; }
        public string CompanyName { get; set; }
        public string CompanyWebUrl { get; set; }
        public string CompanyAddress { get; set; }
        public DateTime? MailUnsubscribeDate { get; set; }
        public DateTime? SmsUnsubscribeDate { get; set; }
        public DateTime? UssdUnsubscribeDate { get; set; }
        public string Projects { get; set; }
        public int FormId { get; set; }
        public string AllFormIds { get; set; }
        public int ChatId { get; set; }
        public string AllChatIds { get; set; }
        public int IsNewLead { get; set; }
        public string EnquiryType { get; set; }
        public string CallStatus { get; set; }
        public string LostReason { get; set; }
        public DateTime? SiteVisitDate { get; set; }
        public string FloorPreference { get; set; }
        public string LocationPreference { get; set; }
        public string PreferenceHouseType { get; set; }
        public string ReasonForFollowUp { get; set; }
        public DateTime? PurchasePlanDate { get; set; }
        public bool? IsSiteVisitBooked { get; set; }
        public bool? IsSiteVisitCompleted { get; set; }
        public bool? IsWhatsAppOptIn { get; set; }
        public DateTime? WhatsAppConsentDate { get; set; }
        public DateTime? ScoreUpdatedDate { get; set; }
        public string LeadLabel { get; set; }
        public string FollowUpContent { get; set; }
        public short? FollowUpStatus { get; set; }
        public DateTime? FollowUpDate { get; set; }
        public int FollowUpUserId { get; set; }
        public DateTime? FollowUpUpdatedDate { get; set; }
        public DateTime? LeadLabelUpdatedDate { get; set; }
        public DateTime? FollowUpCreatedDate { get; set; }
        public DateTime? HandledByUpdatedDate { get; set; }
        public int CreatedUserInfoUserId { get; set; }
        public bool? IsSourceMoved { get; set; }
        public DateTime? SourceMovedDate { get; set; }
        public Int16 RepeatLeadCount { get; set; }
        public int LeadScore { get; set; }
        public string? CustomField1 { get; set; }
        public string? CustomField2 { get; set; }
        public string? CustomField3 { get; set; }
        public string CustomField4 { get; set; }
        public string CustomField5 { get; set; }
        public string CustomField6 { get; set; }
        public string CustomField7 { get; set; }
        public string CustomField8 { get; set; }
        public string CustomField9 { get; set; }
        public string CustomField10 { get; set; }
        public string CustomField11 { get; set; }
        public string CustomField12 { get; set; }
        public string CustomField13 { get; set; }
        public string CustomField14 { get; set; }
        public string CustomField15 { get; set; }
        public string CustomField16 { get; set; }
        public string CustomField17 { get; set; }
        public string CustomField18 { get; set; }
        public string CustomField19 { get; set; }
        public string CustomField20 { get; set; }
        public string CustomField21 { get; set; }
        public string CustomField22 { get; set; }
        public string CustomField23 { get; set; }
        public string CustomField24 { get; set; }
        public string CustomField25 { get; set; }
        public string CustomField26 { get; set; }
        public string CustomField27 { get; set; }
        public string CustomField28 { get; set; }
        public string CustomField29 { get; set; }
        public string CustomField30 { get; set; }
        public string CustomField31 { get; set; }
        public string CustomField32 { get; set; }
        public string CustomField33 { get; set; }
        public string CustomField34 { get; set; }
        public string CustomField35 { get; set; }
        public string CustomField36 { get; set; }
        public string CustomField37 { get; set; }
        public string CustomField38 { get; set; }
        public string CustomField39 { get; set; }
        public string CustomField40 { get; set; }
        public string CustomField41 { get; set; }
        public string CustomField42 { get; set; }
        public string CustomField43 { get; set; }
        public string CustomField44 { get; set; }
        public string CustomField45 { get; set; }
        public string CustomField46 { get; set; }
        public string CustomField47 { get; set; }
        public string CustomField48 { get; set; }
        public string CustomField49 { get; set; }
        public string CustomField50 { get; set; }
        public string CustomField51 { get; set; }
        public string CustomField52 { get; set; }
        public string CustomField53 { get; set; }
        public string CustomField54 { get; set; }
        public string CustomField55 { get; set; }
        public string CustomField56 { get; set; }
        public string CustomField57 { get; set; }
        public string CustomField58 { get; set; }
        public string CustomField59 { get; set; }
        public string CustomField60 { get; set; }
        public string CustomField61 { get; set; }
        public string CustomField62 { get; set; }
        public string CustomField63 { get; set; }
        public string CustomField64 { get; set; }
        public string CustomField65 { get; set; }
        public string CustomField66 { get; set; }
        public string CustomField67 { get; set; }
        public string CustomField68 { get; set; }
        public string CustomField69 { get; set; }
        public string CustomField70 { get; set; }
        public string CustomField71 { get; set; }
        public string CustomField72 { get; set; }
        public string CustomField73 { get; set; }
        public string CustomField74 { get; set; }
        public string CustomField75 { get; set; }
        public string CustomField76 { get; set; }
        public string CustomField77 { get; set; }
        public string CustomField78 { get; set; }
        public string CustomField79 { get; set; }
        public string CustomField80 { get; set; }
        public string CustomField81 { get; set; }
        public string CustomField82 { get; set; }
        public string CustomField83 { get; set; }
        public string CustomField84 { get; set; }
        public string CustomField85 { get; set; }
        public string CustomField86 { get; set; }
        public string CustomField87 { get; set; }
        public string CustomField88 { get; set; }
        public string CustomField89 { get; set; }
        public string CustomField90 { get; set; }
        public string CustomField91 { get; set; }
        public string CustomField92 { get; set; }
        public string CustomField93 { get; set; }
        public string CustomField94 { get; set; }
        public string CustomField95 { get; set; }
        public string CustomField96 { get; set; }
        public string CustomField97 { get; set; }
        public string CustomField98 { get; set; }
        public string CustomField99 { get; set; }
        public string CustomField100 { get; set; }
    }
}
