using System;

namespace P5GenralML
{
    public class FormRules
    {
        public Int32 FormId { get; set; }
        public Int16 IsLead { get; set; }
        public short IsBelong { get; set; }
        public string? BelongsToGroup { get; set; }
        public short BehavioralScoreCondition { get; set; }
        public Int16 BehavioralScore1 { get; set; }
        public Int16 BehavioralScore2 { get; set; }
        public Int16 SessionIs { get; set; }
        public bool SessionConditionIsTrueOrIsFalse { get; set; }
        public Int16 PageDepthIs { get; set; }
        public bool PageDepthConditionIsTrueOrIsFalse { get; set; }
        public Int16 NPageVisited { get; set; }
        public Int16 FrequencyIs { get; set; }
        public string? PageUrl { get; set; }
        public bool IsPageUrlContainsCondition { get; set; }
        public short IsReferrer { get; set; }
        public string? ReferrerUrl { get; set; }
        public bool CheckSourceDomainOnly { get; set; }
        public bool IsMailIsRespondent { get; set; }
        public string? SearchString { get; set; }
        public string? Country { get; set; }
        public string? StateName { get; set; }
        public string? City { get; set; }
        public string? IsClickedSpecificButtons { get; set; }
        public string? ClickedPriceRangeProduct { get; set; }
        public bool IsVisitorRespondedChat { get; set; }
        public short MailCampignResponsiveStage { get; set; }
        public Int32 IsRespondedForm { get; set; }
        public Int32 IsNotRespondedForm { get; set; }
        public Int16 CloseCount { get; set; }
        public string? AddedProductsToCart { get; set; }
        public string? ViewedButNotAddedProductsToCart { get; set; }
        public string? DroppedProductsFromCart { get; set; }
        public string? PurchasedProducts { get; set; }
        public string? NotPurchasedProducts { get; set; }
        public short TotalPurchaseQtyConditon { get; set; }
        public Int16 CustomerTotalPurchase1 { get; set; }
        public Int16 CustomerTotalPurchase2 { get; set; }
        public short TotalPurchaseAmtCondition { get; set; }
        public Int16 CustomerCurrentValue1 { get; set; }
        public Int16 CustomerCurrentValue2 { get; set; }
        public Int32 DependencyFormId { get; set; }
        public Int16 DependencyFormField { get; set; }
        public Int16 DependencyFormCondition { get; set; }
        public string? DependencyFormAnswer1 { get; set; }
        public string? DependencyFormAnswer2 { get; set; }
        public Int32 ImpressionEventForFormId { get; set; }
        public Int16 ImpressionEventCountCondition { get; set; }
        public Int32 CloseEventForFormId { get; set; }
        public Int16 CloseEventCountCondition { get; set; }
        public Int32 ResponsesEventForFormId { get; set; }
        public Int16 ResponsesEventCountCondition { get; set; }
        public short OnlineSentimentIs { get; set; }
        public short SocialStatusIs { get; set; }
        public short InfluentialScoreCondition { get; set; }
        public Int16 InfluentialScore1 { get; set; }
        public Int16 InfluentialScore2 { get; set; }
        public short OfflineSentimentIs { get; set; }
        public short ProductRatingIs { get; set; }
        public string? GenderIs { get; set; }
        public short MaritalStatusIs { get; set; }
        public string? ProfessionIs { get; set; }
        public short NotConnectedSocially { get; set; }
        public short LoyaltyPointsCondition { get; set; }
        public Int16 LoyaltyPointsRange1 { get; set; }
        public Int16 LoyaltyPointsRange2 { get; set; }
        public short RFMSScoreRangeCondition { get; set; }
        public Int16 RFMSScoreRange1 { get; set; }
        public Int16 RFMSScoreRange2 { get; set; }
        public Int32 ShowFormOnlyNthTime { get; set; }
        public bool CloseCountSessionWiseOrOverAll { get; set; }
        public Int16 OverAllTimeSpentInSite { get; set; }
        public string? AlreadyVisitedPages { get; set; }
        public bool PageViewConditionIsTrueOrIsFalse { get; set; }
        public bool FrequencyConditionIsTrueOrIsFalse { get; set; }
        public bool MailRespondentConditionIsTrueOrIsFalse { get; set; }
        public bool CountryConditionIsTrueOrIsFalse { get; set; }
        public bool CityConditionIsTrueOrIsFalse { get; set; }
        public bool StateConditionIsTrueOrIsFalse { get; set; }
        public Int16 NurtureStatusIs { get; set; }
        public short IsMobileDevice { get; set; }
        // public bool AlreadyVisitedPagesConditionIsTrueOrIsFalse { get; set; }

        public bool AlreadyVisitedPagesOverAllOrSessionWise { get; set; }

        public bool ClickedRecentButtonOrOverAll { get; set; }
        public string? ExceptionPageUrl { get; set; }
        public bool IsExceptionPageUrlContainsCondition { get; set; }
        public string? AddedProductsCategoriesToCart { get; set; }
        public string? NotAddedProductsCategoriesToCart { get; set; }
        public string? AddedProductsSubCategoriesToCart { get; set; }
        public string? NotAddedProductsSubCategoriesToCart { get; set; }
        public string? MailRespondentTemplates { get; set; }
        public bool IsSmsIsRespondent { get; set; }
        public bool SmsRespondentConditionIsTrueOrIsFalse { get; set; }
        public string? SmsRespondentTemplates { get; set; }
        public bool IsMailRespondentClickCondition { get; set; }
        public bool IsBirthDay { get; set; }
        public short IsDOBTodayOrMonth { get; set; }
        public string? NotAlreadyVisitedPages { get; set; }
        public bool NotAlreadyVisitedPagesOverAllOrSessionWise { get; set; }
        public DateTime? DOBFromDate { get; set; }
        public DateTime? DOBToDate { get; set; }
        public Int16 DOBDaysDiffernce { get; set; }
        public bool? IsDOBIgnored { get; set; }
        public short IsDOBIgnoreCondition { get; set; }
        public Int16 OverAllTimeSpentInSiteLess { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool IsVisitedPagesContainsCondition { get; set; }
        public bool IsNotVisitedPagesContainsCondition { get; set; }
        public string? PageUrlParameters { get; set; }
        public string? AlreadyVisitedWithPageUrlParameters { get; set; }
        public string? NotAlreadyVisitedWithPageUrlParameters { get; set; }
        public bool IsVisitorVisitedPagesWithPageUrlParameter { get; set; }
        public bool IsVisitorsSource { get; set; }
        public bool IsFormDisplayDurationRecurring { get; set; }
        public short IsBelongToDynamicGrp { get; set; }
        public string? BelongsToDynamicGroup { get; set; }
    }
}
