using System;

namespace P5GenralML
{
    public class MLContact
    {
        public int LastModifyByUserId { get; set; }
        public int UserInfoUserId { get; set; }
        public int UserGroupId { get; set; }
        public int ContactId { get; set; }
        public int LmsGroupId { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public string CustomField4 { get; set; }
        public string CustomField5 { get; set; }
        public string CustomField6 { get; set; }
        public string CustomField7 { get; set; }
        public string CustomField8 { get; set; }
        public string CustomField9 { get; set; }
        public string CustomField10 { get; set; }
        public string CustomField11 { get; set; }
        public string CustomField12 { get; set; }
        public string CustomField13 { get; set; }
        public string CustomField14 { get; set; }
        public string CustomField15 { get; set; }
        public string CustomField16 { get; set; }
        public string CustomField17 { get; set; }
        public string CustomField18 { get; set; }
        public string CustomField19 { get; set; }
        public string CustomField20 { get; set; }
        public string CustomField21 { get; set; }
        public string CustomField22 { get; set; }
        public string CustomField23 { get; set; }
        public string CustomField24 { get; set; }
        public string CustomField25 { get; set; }
        public string CustomField26 { get; set; }
        public string CustomField27 { get; set; }
        public string CustomField28 { get; set; }
        public string CustomField29 { get; set; }
        public string CustomField30 { get; set; }
        public string CustomField31 { get; set; }
        public string CustomField32 { get; set; }
        public string CustomField33 { get; set; }
        public string CustomField34 { get; set; }
        public string CustomField35 { get; set; }
        public string CustomField36 { get; set; }
        public string CustomField37 { get; set; }
        public string CustomField38 { get; set; }
        public string CustomField39 { get; set; }
        public string CustomField40 { get; set; }
        public string CustomField41 { get; set; }
        public string CustomField42 { get; set; }
        public string CustomField43 { get; set; }
        public string CustomField44 { get; set; }
        public string CustomField45 { get; set; }
        public string CustomField46 { get; set; }
        public string CustomField47 { get; set; }
        public string CustomField48 { get; set; }
        public string CustomField49 { get; set; }
        public string CustomField50 { get; set; }
        public string CustomField51 { get; set; }
        public string CustomField52 { get; set; }
        public string CustomField53 { get; set; }
        public string CustomField54 { get; set; }
        public string CustomField55 { get; set; }
        public string CustomField56 { get; set; }
        public string CustomField57 { get; set; }
        public string CustomField58 { get; set; }
        public string CustomField59 { get; set; }
        public string CustomField60 { get; set; }

        public string Remarks { get; set; }
        public DateTime? ReminderDate { get; set; }
        public string ToReminderPhoneNumber { get; set; }
        public string ToReminderEmailId { get; set; }
        public int Score { get; set; }
        public string SearchKeyword { get; set; }
        public string PageUrl { get; set; }
        public string ReferrerUrl { get; set; }
        public Int16 IsAdSenseOrAdWord { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public string Name { get; set; }
        public string EmailId { get; set; }
        public string PhoneNumber { get; set; }
        public string AlternateEmailIds { get; set; }
        public string AlternatePhoneNumbers { get; set; }
        public string LmsGroupName { get; set; }
        public string Place { get; set; }
        public string Notes { get; set; }

        public int MailTemplateId { get; set; }
        public DateTime? MailAlertScheduleDate { get; set; }
        public string FromEmailId { get; set; }
        public string Subject { get; set; }
        public string FromName { get; set; }

        public int SMSTemplateId { get; set; }
        public DateTime? SmsAlertScheduleDate { get; set; }
        public string CustomSmsContent { get; set; }

        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string StateName { get; set; }
        public string DomainName { get; set; }
        public string Religion { get; set; }
        public string ZipCode { get; set; }
        public string CompanyWebUrl { get; set; }
        public string CompanyAddress { get; set; }
        public string Projects { get; set; }
        public string MaritalStatus { get; set; }
        public string Interests { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public string Location { get; set; }
        public Nullable<DateTime> Age { get; set; }
        public string LastName { get; set; }
        public int IsNewLead { get; set; }
        public DateTime? ScoreUpdatedDate { get; set; }
        public string LeadLabel { get; set; }
        public string FollowUpContent { get; set; }
        public Int16 FollowUpStatus { get; set; }
        public DateTime? FollowUpDate { get; set; }
        public int FollowUpUserId { get; set; }
        public DateTime? FollowUpUpdatedDate { get; set; }
        public DateTime? LeadLabelUpdatedDate { get; set; }
        public DateTime? FollowUpCreatedDate { get; set; }
        public DateTime? HandledByUpdatedDate { get; set; }
        public int CreatedUserInfoUserId { get; set; }
        public bool? IsSourceMoved { get; set; }
        public Int16 RepeatLeadCount { get; set; }
        public string CustomField61 { get; set; }
        public string CustomField62 { get; set; }
        public string CustomField63 { get; set; }
        public string CustomField64 { get; set; }
        public string CustomField65 { get; set; }
        public string CustomField66 { get; set; }
        public string CustomField67 { get; set; }
        public string CustomField68 { get; set; }
        public string CustomField69 { get; set; }
        public string CustomField70 { get; set; }
        public string CustomField71 { get; set; }
        public string CustomField72 { get; set; }
        public string CustomField73 { get; set; }
        public string CustomField74 { get; set; }
        public string CustomField75 { get; set; }
        public string CustomField76 { get; set; }
        public string CustomField77 { get; set; }
        public string CustomField78 { get; set; }
        public string CustomField79 { get; set; }
        public string CustomField80 { get; set; }
        public string CustomField81 { get; set; }
        public string CustomField82 { get; set; }
        public string CustomField83 { get; set; }
        public string CustomField84 { get; set; }
        public string CustomField85 { get; set; }
        public string CustomField86 { get; set; }
        public string CustomField87 { get; set; }
        public string CustomField88 { get; set; }
        public string CustomField89 { get; set; }
        public string CustomField90 { get; set; }
        public string CustomField91 { get; set; }
        public string CustomField92 { get; set; }
        public string CustomField93 { get; set; }
        public string CustomField94 { get; set; }
        public string CustomField95 { get; set; }
        public string CustomField96 { get; set; }
        public string CustomField97 { get; set; }
        public string CustomField98 { get; set; }
        public string CustomField99 { get; set; }
        public string CustomField100 { get; set; }
        public string FirstUtmMedium { get; set; }
        public string FirstUtmCampaign { get; set; }
        public string FirstUtmTerm { get; set; }
        public string FirstUtmContent { get; set; }
        public bool? IsWhatsAppOptIn { get; set; }
        public int Revenue { get; set; }
        public DateTime? ClouserDate { get; set; }
        public string CountryCode { get; set; }
        public int LmsGroupmemberId { get; set; }
    }
}
