using System;

namespace P5GenralML
{
    public class ProductOfferForContact
    {
        public int? ContactId { get; set; }
        public string MemberId { get; set; }
        public string ApplicantId { get; set; }
        public string ProspectId { get; set; }
        public decimal? CLOSED_OFFERAMT { get; set; }
        public decimal? CLOSED_OFFEREMI { get; set; }
        public decimal? DIGI_OFFERAMT { get; set; }
        public string DIGIGOLD_FLAG { get; set; }
        public string EMISTORE_A2C_DESC { get; set; }
        public decimal? EMISTORE_AGREEMENT_NO { get; set; }
        public decimal? EMISTORE_AVAIL_LIMIT { get; set; }
        public string EMISTORE_BUYERTYPE { get; set; }
        public string EMISTORE_CANCEL_ORDER { get; set; }
        public decimal? EMISTORE_CARDNUMBER { get; set; }
        public string EMISTORE_DATE { get; set; }
        public decimal? EMISTORE_EMI { get; set; }
        public string EMISTORE_FS_DESC { get; set; }
        public string EMISTORE_Holder_1 { get; set; }
        public string EMISTORE_Holder_2 { get; set; }
        public decimal? EMISTORE_OFFERAMT { get; set; }
        public decimal? EMISTORE_ORDER_ID { get; set; }
        public string EMISTORE_OUTOFSTOCK_TRANS { get; set; }
        public string EMISTORE_PDP_DESC { get; set; }
        public string EMISTORE_PRIORITY { get; set; }
        public string EMISTORE_PRODUCTNAME { get; set; }
        public string EMISTORE_REMARKETING { get; set; }
        public string EMISTORE_TOP30DEALER { get; set; }
        public string EMISTORE_URL { get; set; }
        public string FD_OFFERID { get; set; }
        public string INS_2W { get; set; }
        public string INS_2W_OFFERID { get; set; }
        public DateTime? INS_2W_RENEWAL_DATE { get; set; }
        public string INS_2W_RENEWAL_FLAG { get; set; }
        public string INS_2W_RENEWAL_MONTH { get; set; }
        public decimal? INS_2W_VEHICLEAGE { get; set; }
        public string INS_4W { get; set; }
        public string INS_4W_2W_DATATYPE { get; set; }
        public string INS_4W_CARSEG { get; set; }
        public string INS_4W_OFFERID { get; set; }
        public string INS_4W_RENEW_FLAG { get; set; }
        public DateTime? INS_4W_RENEWAL_DATE { get; set; }
        public string INS_4W_RENEWAL_MONTH { get; set; }
        public decimal? INS_4W_VEHICLEAGE { get; set; }
        public string INS_DATA_TYPE { get; set; }
        public string INS_DATA_SOURCE { get; set; }
        public string INS_EMICARD_FLAG { get; set; }
        public string INS_GTL { get; set; }
        public decimal? INS_GTL_OFFER_AMOUNT { get; set; }
        public string INS_GTL_OFFER_ID { get; set; }
        public string INS_HEALTH { get; set; }
        public string INS_HEALTH_OFFERID { get; set; }
        public string INS_HEALTH_PRIORITY { get; set; }
        public string INS_OTHER_CAMP_FLAG { get; set; }
        public string INS_PRIORITY { get; set; }
        public string INS_SOURCE { get; set; }
        public string INS_TOPUP { get; set; }
        public string INS_TRAVEL { get; set; }
        public string INS_ULIP { get; set; }
        public string INS_ULIP_OFFERID { get; set; }
        public string INS_ULIP_PRIORITY { get; set; }
        public string LAPBT_OFFERID { get; set; }
        public string LAPFRESH_OFFERID { get; set; }
        public decimal? NSB_AMT { get; set; }
        public decimal? NSB_AVL_LIMIT { get; set; }
        public string NSB_QKR { get; set; }
        public string NSB_REFID { get; set; }
        public string NSB_URL { get; set; }
        public string OFFER_PRODUCT { get; set; }
        public string PLTB_OFFER { get; set; }
        public string REMARKETING_UNSECLANO { get; set; }
        public string SEC_ACC_NO { get; set; }
        public string SEC_AUTO_TOPUP_OFFER { get; set; }
        public decimal? SEC_AUTO_TOPUP_OFFER_LACS { get; set; }
        public string SEC_HL_OFFERID { get; set; }
        public decimal? SEC_HL_PREAPP_AMT { get; set; }
        public decimal? SEC_HL_PREAPP_AMT_LACS { get; set; }
        public string SEC_HL_RESP { get; set; }
        public string SEC_HL_SOURCE { get; set; }
        public string SEC_HL_ZONE { get; set; }
        public decimal? SEC_HLBT_BT_EMI { get; set; }
        public string SEC_HLBT_BT_OFFER { get; set; }
        public decimal? SEC_HLBT_BT_SAVINGS { get; set; }
        public string SEC_HLBT_CAMFILTER { get; set; }
        public string SEC_HLBT_CATEGORY { get; set; }
        public string SEC_HLBT_GENPOOL { get; set; }
        public string SEC_HLBT_OFFERID { get; set; }
        public decimal? SEC_HLBT_PLENQ { get; set; }
        public string SEC_HLBT_PRIORITY { get; set; }
        public string SEC_HLBT_RESPSEG { get; set; }
        public string SEC_HLBT_SOURCE { get; set; }
        public decimal? SEC_HLBT_TOPUP { get; set; }
        public decimal? SEC_HLBT_TOPUP_LACS { get; set; }
        public string SEC_HLBT_TOTAL_OFFER { get; set; }
        public decimal? SEC_HLBT_TOTAL_OFFER_LACS { get; set; }
        public string SEC_LANO { get; set; }
        public decimal? SEC_LAP_SAVINGS_OBLIGATION { get; set; }
        public decimal? SEC_LAPBT_BT_EMI { get; set; }
        public decimal? SEC_LAPBT_BT_SAVINGS { get; set; }
        public string SEC_LAPBT_OFFER { get; set; }
        public string SEC_LAPBT_RESPSEG { get; set; }
        public string SEC_LAPBT_SOURCE { get; set; }
        public decimal? SEC_LAPBT_TOPUP { get; set; }
        public decimal? SEC_LAPBT_TOPUP_OFFER { get; set; }
        public decimal? SEC_LAPBT_TOTAL_OFFER { get; set; }
        public decimal? SEC_LAPBT_TP_LACS { get; set; }
        public decimal? SEC_LAPFRESH_INLACS_OFFERAMT { get; set; }
        public decimal? SEC_LAPFRESH_OFFER { get; set; }
        public decimal? SEC_LAPFRESH_OFFER_INLACS { get; set; }
        public string SEC_LAPFRESH_RESPONSE_FLAG { get; set; }
        public string SEC_LAPFRESH_RESPSEG { get; set; }
        public string SEC_LAPFRESH_SOURCE { get; set; }
        public decimal? SEC_LAPFRESH_TOTAL_OFFER { get; set; }
        public decimal? SEC_LINE_OFFERAMT { get; set; }
        public string SEC_SHOL_REMARKETING { get; set; }
        public decimal? UNSEC_AVAIL_LIMIT { get; set; }
        public string UNSEC_CAMPFREQ { get; set; }
        public string UNSEC_CROSSSELL { get; set; }
        public string UNSEC_DBOL_PROL { get; set; }
        public decimal? UNSEC_DBOL_PROL_AMT { get; set; }
        public string UNSEC_DBOL_PROL_OFFERID { get; set; }
        public string UNSEC_DBOL_PROL_POOL { get; set; }
        public string UNSEC_DBOL_PROL_PRIORITY { get; set; }
        public string UNSEC_DBOL_PROL_URL { get; set; }
        public string UNSEC_LAN { get; set; }
        public string UNSEC_LOANBRACKET { get; set; }
        public string UNSEC_OFFER { get; set; }
        public decimal? UNSEC_PL_OFFEREMI1 { get; set; }
        public decimal? UNSEC_PL_SAVING1 { get; set; }
        public decimal? UNSEC_PL1_LOANAMT { get; set; }
        public decimal? UNSEC_PREAQAMT { get; set; }
        public decimal? UNSEC_PREQAMT { get; set; }
        public string UNSEC_PRIORITY { get; set; }
        public string UNSEC_RDATA { get; set; }
        public string UNSEC_REMARKETING { get; set; }
        public decimal? UNSEC_SAVING1 { get; set; }
        public string UNSEC_SOL_OFFERID { get; set; }
        public decimal? UNSEC_SOL_PREAQAMT { get; set; }
        public decimal? UNSEC_SOL_PREAQEMI { get; set; }
        public decimal? UNSEC_SOL_PREAQOFFEREMI { get; set; }
        public decimal? UNSEC_SOL_PREAQSAVE { get; set; }
        public string UNSEC_SOURCE { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
}
